### ISSUE TITLE
 list index out of range

### ISSUE THREAD

**Issue by dreamfuluser** [nlpyang/BertSum#10]
File "D:/untitled/BertSum-master/src/train.py", line 349, in <module>
    step = int(cp.split('.')[-2].split('_')[-1])
IndexError: list index out of range

what should i do ?
thanks...

**Comment by angeluau** [comment]
try in the state of test?

**Comment by angeluau** [comment]
i still encounter this problem

**Comment by dreamfuluser** [comment]
> try in the state of test?



> try in the state of test?

yep,just happens in the test state
Is data problem?

**Comment by nlpyang** [comment]
This should be solved now.
If not, please paste your commands

**Comment by tanmaypandey7** [comment]
training it on google colab:
directory structure as :
-->BertSum
        ├── bert_data
        ├── (other BertSum repo files)


added system path as 
```
import sys
sys.path.append('/content/BertSum/src')
```

On running this on colab:
`!python train.py -mode train -encoder transformer -dropout 0.1 -bert_data_path ../bert_data/cnndm -model_path ../models/bert_transformer -lr 2e-3 -visible_gpus 0  -gpu_ranks 0 -world_size 3 -report_every 50 -save_checkpoint_steps 1000 -batch_size 3000 -decay_method noam -train_steps 50000 -accum_count 2 -log_file ../logs/bert_transformer -use_interval true -warmup_steps 10000 -ff_size 2048 -inter_layers 2 -heads 8`

(i keyboard interrupted this)
```
[2019-07-17 12:03:24,228 INFO]  Starting process pid: 759  
[2019-07-17 12:03:24,233 INFO]  Starting process pid: 760  
[2019-07-17 12:03:24,241 INFO]  Starting process pid: 761  
[0]
Process SpawnProcess-2:
Traceback (most recent call last):
  File "/content/BertSum/src/train.py", line 68, in run
    gpu_rank = distributed.multi_init(device_id, args.world_size, args.gpu_ranks)
  File "/content/BertSum/src/distributed.py", line 27, in multi_init
    world_size=dist_world_size, rank=gpu_ranks[device_id])
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/content/BertSum/src/train.py", line 80, in run
    error_queue.put((args.gpu_ranks[device_id], traceback.format_exc()))
IndexError: list index out of range
[0]
[0]
Process SpawnProcess-3:
Traceback (most recent call last):
  File "/content/BertSum/src/train.py", line 68, in run
    gpu_rank = distributed.multi_init(device_id, args.world_size, args.gpu_ranks)
  File "/content/BertSum/src/distributed.py", line 27, in multi_init
    world_size=dist_world_size, rank=gpu_ranks[device_id])
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/content/BertSum/src/train.py", line 80, in run
    error_queue.put((args.gpu_ranks[device_id], traceback.format_exc()))
IndexError: list index out of range
Traceback (most recent call last):
  File "train.py", line 338, in <module>
    multi_main(args)
  File "train.py", line 58, in multi_main
```
On changing  `visible_gpus 0` to  `visible_gpus 0,1` the error remains the same.

**Comment by nlpyang** [comment]
world_size should be the number of gpus you are using
