### ISSUE TITLE
Problem of processed data

### ISSUE THREAD

**Issue by perthrocky** [nlpyang/BertSum#28]
Hi,

I clone the git, then download the processed data, then run the cmd:
----------- cmd-----------
python train.py -mode train -encoder rnn -dropout 0.1 -bert_data_path ../bert_data/cnndm -model_path ../models/bert_classifier -lr 2e-3 -visible_gpus 0  -gpu_ranks 0 -world_size 1 -report_every 50 -save_checkpoint_steps 1000 -batch_size 64 -decay_method noam -train_steps 5120 -accum_count 2 -log_file ../logs/bert_classifier -use_interval true -warmup_steps 256
----------- cmd-----------

I got this error:
------------error------------
[2019-05-14 03:21:58,963 INFO] Start training...
[2019-05-14 03:21:59,150 INFO] Loading train dataset from ../bert_data_tmp/cnndm.train.0.bert.pt, number of examples: 2001
Traceback (most recent call last):
  File "train.py", line 340, in <module>
    train(args, device_id)
  File "train.py", line 272, in train
    trainer.train(train_iter_fct, args.train_steps)
  File "/notebooks/workspace/git/BertSum/src/models/trainer.py", line 158, in train
    report_stats)
  File "/notebooks/workspace/git/BertSum/src/models/trainer.py", line 323, in _gradient_accumulation
    sent_scores, mask = self.model(src, segs, clss, mask, mask_cls)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/notebooks/workspace/git/BertSum/src/models/model_builder.py", line 96, in forward
    sent_scores = self.encoder(sents_vec, mask_cls).squeeze(-1)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/notebooks/workspace/git/BertSum/src/models/encoder.py", line 129, in forward
    memory_bank = self.dropout(memory_bank) + x
RuntimeError: The size of tensor a (512) must match the size of tensor b (768) at non-singleton dimension 2
------------error------------

**Comment by uHm1995** [comment]
you need to set the gpu_rank = 0
