### ISSUE TITLE
Format JSON file to Pytorch File

### ISSUE THREAD

**Issue by Motta23** [nlpyang/BertSum#36]
First of all, many thanks for the code!

I am trying to convert the sample json file in the ../json_data directory to a Pytorch file in the ../bert_data directory (testing this out so I can use my own text in JSON format:

```
python preprocess.py -mode format_to_bert -oracle_mode greedy -n_cpus 4 -log_file ../logs/preprocess.log
```

However, the code doesn't seem to do much. I get the following back:
```
[('../json_data\\cnndm_sample.train.0.json', Namespace(dataset='', log_file='../logs/preprocess.log', lower=True, map_path='../data/', max_nsents=100, max_src_ntokens=200, min_nsents=3, min_src_ntokens=5, mode='format_to_bert', n_cpus=4, oracle_mode='greedy', raw_path='../json_data/', save_path='../bert_data/', shard_size=2000), '../bert_data/bert.pt_data\\c
nndm_sample.train.0.bert.pt')]

```

And it has been stuck on this for the last 2/3 hours. I would think that converting the .json files to .pt shouldn't take this long (also my CPU's are not utilized at all). Have you encountered this?

**Comment by nlpyang** [comment]
Not sure what you encountered here. I ran the same code and get the correct results in seconds.

**Comment by Motta23** [comment]
Thank you for the very quick reply and testing it out. I probably have a misconfiguration in my Windows somewhere as I installed a Linux VirtualBox and it runs there smoothly as well.

**Comment by makamkkumar** [comment]
I am getting the following error myself I think there is something a miss
gpu_rank 0
[2019-06-25 15:25:49,112 INFO] * number of parameters: 109483009
[2019-06-25 15:25:49,113 INFO] Start training...
[2019-06-25 15:25:49,218 INFO] Loading train dataset from ../bert_data/cnndm.train.123.bert.pt, number of examples: 2001
Traceback (most recent call last):
  File "train.py", line 340, in <module>
    train(args, device_id)
  File "train.py", line 272, in train
    trainer.train(train_iter_fct, args.train_steps)
  File "/home/kiran1/KiranResearch/BertSum/src/models/trainer.py", line 157, in train
    report_stats)
  File "/home/kiran1/KiranResearch/BertSum/src/models/trainer.py", line 321, in _gradient_accumulation
    sent_scores, mask = self.model(src, segs, clss, mask, mask_cls)
  File "/home/kiran1/Downloads/yes/envs/pointer/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kiran1/KiranResearch/BertSum/src/models/model_builder.py", line 93, in forward
    top_vec = self.bert(x, segs, mask)
  File "/home/kiran1/Downloads/yes/envs/pointer/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kiran1/KiranResearch/BertSum/src/models/model_builder.py", line 52, in forward
    encoded_layers, _ = self.model(x, segs, attention_mask =mask)
  File "/home/kiran1/Downloads/yes/envs/pointer/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kiran1/Downloads/yes/envs/pointer/lib/python3.7/site-packages/pytorch_pretrained_bert/modeling.py", line 733, in forward
    output_all_encoded_layers=output_all_encoded_layers)
  File "/home/kiran1/Downloads/yes/envs/pointer/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kiran1/Downloads/yes/envs/pointer/lib/python3.7/site-packages/pytorch_pretrained_bert/modeling.py", line 406, in forward
    hidden_states = layer_module(hidden_states, attention_mask)
  File "/home/kiran1/Downloads/yes/envs/pointer/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kiran1/Downloads/yes/envs/pointer/lib/python3.7/site-packages/pytorch_pretrained_bert/modeling.py", line 391, in forward
    attention_output = self.attention(hidden_states, attention_mask)
  File "/home/kiran1/Downloads/yes/envs/pointer/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kiran1/Downloads/yes/envs/pointer/lib/python3.7/site-packages/pytorch_pretrained_bert/modeling.py", line 349, in forward
    self_output = self.self(input_tensor, attention_mask)
  File "/home/kiran1/Downloads/yes/envs/pointer/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kiran1/Downloads/yes/envs/pointer/lib/python3.7/site-packages/pytorch_pretrained_bert/modeling.py", line 310, in forward
    attention_scores = attention_scores / math.sqrt(self.attention_head_size)
RuntimeError: CUDA out of memory. Tried to allocate 60.00 MiB (GPU 0; 7.92 GiB total capacity; 6.31 GiB already allocated; 69.31 MiB free; 39.90 MiB cached)

Any solution please advice

**Comment by nlpyang** [comment]
The log already told you that this is a out-of-memory error

**Comment by makamkkumar** [comment]
How can I get summerisation for one article
The pipeline is not working as it requires the urls as the article may not be from internet or have webpage?

**Comment by makamkkumar** [comment]
> The log already told you that this is a out-of-memory error

I reduced the batch size further to get out of the situation. Thanks

**Comment by nimahassanpour** [comment]
> Not sure what you encountered here. I ran the same code and get the correct results in seconds.

I am having another strange problem. When I follow the Option2 for pre-processing data, I can tokenize .story files successfully and generate .story.json file. But When I run the step-5 I always get three empty square bracket:

[nhassanp@uc1f-bioinfocloud-assembly-base src]$ /data/conda_envs/20200204/miniconda3/bin/python preprocess.py -mode format_to_bert -raw_path ../merged_stories_tokenized/ -save_path ../bert_cnn/ -oracle_mode greedy -log_file ../logs/preprocess.log
[]
[]
[]

(Since I don't have url for my data, I skip step-4)

**Comment by AyeshaSarwar** [comment]
I am having the same issue. Did anybody able to resolve it? Anybody can help me regarding this matter. I am also getting these three empty square brackets. What possible error it could be??

**Comment by AyeshaSarwar** [comment]
Also, the parameter oracle_mode is not working for me. It gives an error for wrong arguments.

**Comment by nimahassanpour** [comment]
@AyeshaSarwar I guess your raw_path is empty or is not correct. You may need to change the paths that were defined inside the original code
