### ISSUE TITLE
model training interrupt

### ISSUE THREAD

**Issue by fengzhangyin** [nlpyang/BertSum#6]
Following the readme, I download the processed data and try to train the model by myself.
I use single-GPU to downloading data. After that I rerun the code with multi-GPUs. **The program can start executing, but after a while,  whether it is a single GPU or multiple GPUs,  the following problems always occur.**  The step of running at the time of interruption may be different between different experiments.

[2019-04-04 00:46:20,545 INFO] loading vocabulary file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-vocab.txt from cache at ../temp/26bc1ad6c0ac742e9b52263248f6d0f00068293b33709fae12320c0e35ccfbbb.542ce4285a40d23a559526243235df47c5f75c197f04f37d1a0c124c32c9a084
[2019-04-04 00:46:23,405 INFO] Step 400/50000; xent: 3.30; lr: 0.0000008;  20 docs/s;    368 sec
[2019-04-04 00:47:08,724 INFO] Step 450/50000; xent: 3.33; lr: 0.0000009;  22 docs/s;    413 sec
[2019-04-04 00:47:51,472 INFO] Step 500/50000; xent: 3.19; lr: 0.0000010;  23 docs/s;    456 sec
[2019-04-04 00:48:35,173 INFO] Step 550/50000; xent: 3.22; lr: 0.0000011;  23 docs/s;    500 sec[2019-04-04 00:49:16,433 INFO] Loading train dataset from ../bert_data/cnndm.train.6.bert.pt, number of examples: 2001[2019-04-04 00:49:41,427 ERROR] Model name 'bert-base-uncased' was not found in model name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese). We assumed 'https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-vocab.txt' was a path or url but couldn't find any file associated to this path or url.
Traceback (most recent call last):
  File "train.py", line 335, in <module>
    train(args, device_id)
  File "train.py", line 267, in train
    trainer.train(train_iter_fct, args.train_steps)
  File "/users4/zyfeng/gitcodes/BertSum/src/models/trainer.py", line 142, in train
    for i, batch in enumerate(train_iter):
  File "/users4/zyfeng/gitcodes/BertSum/src/models/data_loader.py", line 141, in __iter__
    self.cur_iter = self._next_dataset_iterator(dataset_iter)
  File "/users4/zyfeng/gitcodes/BertSum/src/models/data_loader.py", line 159, in _next_dataset_iterator
    device=self.device, shuffle=self.shuffle, is_test=self.is_test)
  File "/users4/zyfeng/gitcodes/BertSum/src/models/data_loader.py", line 175, in __init__
    self.bert_data = BertData(args)
  File "/users4/zyfeng/gitcodes/BertSum/src/models/data_loader.py", line 15, in __init__
    self.sep_vid = self.tokenizer.vocab['[SEP]']
AttributeError: 'NoneType' object has no attribute 'vocab'

**The following files is downloaded in temp dir.**

26bc1ad6c0ac742e9b52263248f6d0f00068293b33709fae12320c0e35ccfbbb.542ce4285a40d23a559526243235df47c5f75c197f04f37d1a0c124c32c9a084
26bc1ad6c0ac742e9b52263248f6d0f00068293b33709fae12320c0e35ccfbbb.542ce4285a40d23a559526243235df47c5f75c197f04f37d1a0c124c32c9a084.json
9c41111e2de84547a463fd39217199738d1e3deb72d4fec4399e6e241983c6f0.ae3cef932725ca7a30cdcb93fc6e09150a55e2a130ec7af63975a16c153ae2ba
9c41111e2de84547a463fd39217199738d1e3deb72d4fec4399e6e241983c6f0.ae3cef932725ca7a30cdcb93fc6e09150a55e2a130ec7af63975a16c153ae2ba.json

I am curious about this reason. I don't know  what should I do ?

**Comment by nlpyang** [comment]
This happened when you don't have access to the temp_dir after training.
I have removed the logic for loading the vocabulary in each iteration.
Could you pull the codes and check it is solved?

**Comment by fengzhangyin** [comment]
Thanks you very much. I pull the codes and I can retrain the model.

But when I try to validate the checkpoint, the same problem occurs.

[2019-04-05 11:00:02,207 INFO] * number of parameters: 113041921
[2019-04-05 11:00:40,926 INFO] Loading valid dataset from ../bert_data/cnndm.valid.1.bert.pt, number of examples: 2001
[2019-04-05 11:01:19,612 INFO] Loading valid dataset from ../bert_data/cnndm.valid.2.bert.pt, number of examples: 2001
[2019-04-05 11:01:57,982 INFO] Loading valid dataset from ../bert_data/cnndm.valid.3.bert.pt, number of examples: 2000
[2019-04-05 11:02:36,660 INFO] Loading valid dataset from ../bert_data/cnndm.valid.4.bert.pt, number of examples: 2001
[2019-04-05 11:03:15,177 INFO] Loading valid dataset from ../bert_data/cnndm.valid.5.bert.pt, number of examples: 2001
[2019-04-05 11:03:53,869 INFO] Loading valid dataset from ../bert_data/cnndm.valid.6.bert.pt, number of examples: 1362
[2019-04-05 11:04:19,877 INFO] Validation xent: 6.63551 at step 1000
[2019-04-05 11:04:19,925 INFO] Loading checkpoint from ../models/bert_rnn/model_step_2000.pt
Namespace(accum_count=1, batch_size=30000, bert_data_path='../bert_data/cnndm', beta1=0.9, beta2=0.999, block_trigram=True, dataset='', decay_method='', dropout=0.1, encoder='rnn', ff_size=512, gpu_ranks=[0], heads=4, hidden_size=128, inter_layers=2, large=False, log_file='../logs/valid_bert_rnn', lr=1, max_grad_norm=0, mode='validate', model_path='../models/bert_rnn/', optim='adam', param_init=0, param_init_glorot=True, recall_eval=False, report_every=1, report_rouge=True, result_path='../results/cnndm/bert_rnn', rnn_size=768, save_checkpoint_steps=5, seed=666, temp_dir='../temp', test_all=True, test_from='', train_from='', train_steps=1000, use_interval=True, visible_gpus='5', warmup_steps=8000, world_size=1)
[2019-04-05 11:07:38,183 ERROR] Model name 'bert-base-uncased' was not found in model name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese). We assumed 'https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased.tar.gz' was a path or url but couldn't find any file associated to this path or url.
Traceback (most recent call last):
  File "train.py", line 337, in <module>
    wait_and_validate(args, device_id)
  File "train.py", line 127, in wait_and_validate
    xent = validate(args, device_id, cp, step)
  File "train.py", line 178, in validate
    model = Summarizer(args, device, checkpoint)
  File "/users4/zyfeng/gitcodes/BertSum/src/models/model_builder.py", line 71, in __init__
    input_size=self.bert.model.config.hidden_size, hidden_size=args.rnn_size,
AttributeError: 'NoneType' object has no attribute 'config'

**Comment by nlpyang** [comment]
please change temp_path to someplace you have acess to and use an abosolute path.

The error is related to your system environment.

**Comment by fengzhangyin** [comment]
I am sure I have permission to access to temp_path. 
Moreover, I  have changed temp_path and used an abosolute path. But I still got the same error.
There was no error when I validate the first few checkpoints. Then the program was suddenly interrupted.
Logic is the same as before for loading the valid dataset in each validation. Maybe it is problematic ?

**Comment by nlpyang** [comment]
This happens because there is an environment error when loading bert_model from the temp path. 

For a fix, I changed the logic in dev branch. Please checkout dev and let me know if this is solved.

This never occurred to me or others, I think you should debug carefully to solve this, cause this may still happen when you use pyrouge to evaluate the results.

**Comment by fengzhangyin** [comment]
Thanks.
Using the dev branch, I could only  validate the bert_classifier model.
It did not work for the bert_rnn model and the bert_transformer model.
As you say, I should debug carefully.

**Comment by nlpyang** [comment]
Hi Yin,

Please pull dev again, the model should work fine now.

**Comment by fengzhangyin** [comment]
Yang, thank you very much for your careful guidance.
Now,  all models work fine.

By the way, I think the batch size of the model evaluation part should be 3000. 
What you wrote in the readme is 30000.
